spring:
  profiles:
    include:
      - db
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    com.example: debug

server:
  servlet:
    context-path: /